name: Monthly Cron Job Test

on:
  schedule:
    - cron: '26 21 30 8 *'  # Runs on August 30th at 21:26 UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Print Date
      run: date
